# this is the channel and label where packages will be uploaded to if enabled
# (see ../README.md)
channel_targets:
  - YOUR_ANACONDA_CHANNEL main

# pin to GNU Radio 3.8 for this branch
gnuradio_core:
  - 3.8.*
